### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by Mrfujianfei** [tidepool-org/uploader#1017]
when i run command "npm run dev" on windows。The error message is as follows。
```
Uncaught Error: Could not locate the bindings file. Tried:
 → D:\repository\test\uploader\build\bindings.node
 → D:\repository\test\uploader\build\Debug\bindings.node
 → D:\repository\test\uploader\build\Release\bindings.node
 → D:\repository\test\uploader\out\Debug\bindings.node
 → D:\repository\test\uploader\Debug\bindings.node
 → D:\repository\test\uploader\out\Release\bindings.node
 → D:\repository\test\uploader\Release\bindings.node
 → D:\repository\test\uploader\build\default\bindings.node
 → D:\repository\test\uploader\compiled\12.8.1\win32\x64\bindings.node
 → D:\repository\test\uploader\addon-build\release\install-root\bindings.node
 → D:\repository\test\uploader\addon-build\debug\install-root\bindings.node
 → D:\repository\test\uploader\addon-build\default\install-root\bindings.node
 → D:\repository\test\uploader\lib\binding\node-v75-win32-x64\bindings.node
    at bindings (bindings.js:126)
    at Object../node_modules/@serialport/bindings/lib/win32.js (win32.js:1)
    at __webpack_require__ (bootstrap:726)
    at fn (bootstrap:100)
    at Object../node_modules/@serialport/bindings/lib/index.js (index.js:6)
    at __webpack_require__ (bootstrap:726)
    at fn (bootstrap:100)
    at Object../node_modules/serialport/lib/index.js (index.js:2)
    at __webpack_require__ (bootstrap:726)
    at fn (bootstrap:100)
```
and I do not know How do some of these folders appear。like "build" ,"out","Debug",“Release”......
thanks for you help

**Comment by gniezen** [comment]
It is recommended that you use `yarn` instead of `npm`. First run `yarn` to install all the dependencies, then run `yarn dev` to start the uploader.

**Comment by EugeneChiang123** [comment]
@gniezen when I do what you mentioned. the electron application starts, but no window opens. Terminal says: 'Uploading only new records' 
Nothing response afterwards. The application was running fine with npm start until 2/27

**Comment by gniezen** [comment]
Hi @EugeneChiang123 ! Try deleting the `node_modules` and `app\node_nodules` directories before running `yarn`. Also, I recommend using Node v12.13.0, as that's what's used by internally Electron (it isn't required, but does might help).

**Comment by EugeneChiang123** [comment]
Hello @gniezen 
That part worked, but the  window now appears completely white without anything, and everything seems to stop. I have attached the error messages I received below. I changed my node to 12.13.0 as you mentioned as well as deleting the node_modules and use yarn. I also tried yarn test. All tests pass.
I'm not understanding what these errors mean? or what is causing them.

tiny-warning.cjs.js:13 Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack
warning @ tiny-warning.cjs.js:13
(anonymous) @ history.js:692
confirmTransitionTo @ history.js:168
push @ history.js:671
(anonymous) @ middleware.js:25
(anonymous) @ index.js:14
dispatch @ VM64:1
(anonymous) @ index.js:25
./app/index.js @ renderer.dev.js:7669
__webpack_require__ @ bootstrap:725
fn @ bootstrap:100
0 @ renderer.dev.js:222337
__webpack_require__ @ bootstrap:725
(anonymous) @ bootstrap:792
(anonymous) @ bootstrap:792
internal/fs/utils.js:219 Uncaught Error: ENOENT: no such file or directory, scandir '/resources/mac/helpers/'
    at Object.readdirSync (fs.js:854)
    at Object.fs.readdirSync (electron/js2c/asar.js:605)
    at Object.fs.readdirSync (electron/js2c/asar.js:605)
    at checkVersion (drivers.darwin.js:88)
    at App.componentWillMount (App.js:115)
    at callComponentWillMount (react-dom.development.js:14253)
    at mountClassInstance (react-dom.development.js:14356)
    at updateClassComponent (react-dom.development.js:18394)
    at beginWork$1 (react-dom.development.js:20160)
    at HTMLUnknownElement.callCallback (react-dom.development.js:337)
handleErrorFromBinding @ internal/fs/utils.js:219
readdirSync @ fs.js:854
fs.readdirSync @ electron/js2c/asar.js:605
fs.readdirSync @ electron/js2c/asar.js:605
checkVersion @ drivers.darwin.js:88
componentWillMount @ App.js:115
callComponentWillMount @ react-dom.development.js:14253
mountClassInstance @ react-dom.development.js:14356
updateClassComponent @ react-dom.development.js:18394
beginWork$1 @ react-dom.development.js:20160
callCallback @ react-dom.development.js:337
invokeGuardedCallbackDev @ react-dom.development.js:386
invokeGuardedCallback @ react-dom.development.js:441
beginWork$$1 @ react-dom.development.js:25737
performUnitOfWork @ react-dom.development.js:24661
workLoopSync @ react-dom.development.js:24637
performSyncWorkOnRoot @ react-dom.development.js:24236
scheduleUpdateOnFiber @ react-dom.development.js:23664
updateContainer @ react-dom.development.js:27060
(anonymous) @ react-dom.development.js:27484
unbatchedUpdates @ react-dom.development.js:24399
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27483
render @ react-dom.development.js:27620
(anonymous) @ index.js:36
./app/index.js @ renderer.dev.js:7669
__webpack_require__ @ bootstrap:725
fn @ bootstrap:100
0 @ renderer.dev.js:222337
__webpack_require__ @ bootstrap:725
(anonymous) @ bootstrap:792
(anonymous) @ bootstrap:792
react-dom.development.js:12339 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: App, ConnectedRouter, Route, Router
printWarning @ react-dom.development.js:12339
lowPriorityWarningWithoutStack @ react-dom.development.js:12360
module.exports../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:12524
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:25646
commitRootImpl @ react-dom.development.js:24894
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12131
commitRoot @ react-dom.development.js:24888
finishSyncRender @ react-dom.development.js:24295
performSyncWorkOnRoot @ react-dom.development.js:24273
scheduleUpdateOnFiber @ react-dom.development.js:23664
updateContainer @ react-dom.development.js:27060
(anonymous) @ react-dom.development.js:27484
unbatchedUpdates @ react-dom.development.js:24399
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27483
render @ react-dom.development.js:27620
(anonymous) @ index.js:36
./app/index.js @ renderer.dev.js:7669
__webpack_require__ @ bootstrap:725
fn @ bootstrap:100
0 @ renderer.dev.js:222337
__webpack_require__ @ bootstrap:725
(anonymous) @ bootstrap:792
(anonymous) @ bootstrap:792
react-dom.development.js:12339 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(App), Provider, Route, Router
printWarning @ react-dom.development.js:12339
lowPriorityWarningWithoutStack @ react-dom.development.js:12360
module.exports../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:12530
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:25646
commitRootImpl @ react-dom.development.js:24894
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12131
commitRoot @ react-dom.development.js:24888
finishSyncRender @ react-dom.development.js:24295
performSyncWorkOnRoot @ react-dom.development.js:24273
scheduleUpdateOnFiber @ react-dom.development.js:23664
updateContainer @ react-dom.development.js:27060
(anonymous) @ react-dom.development.js:27484
unbatchedUpdates @ react-dom.development.js:24399
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27483
render @ react-dom.development.js:27620
(anonymous) @ index.js:36
./app/index.js @ renderer.dev.js:7669
__webpack_require__ @ bootstrap:725
fn @ bootstrap:100
0 @ renderer.dev.js:222337
__webpack_require__ @ bootstrap:725
(anonymous) @ bootstrap:792
(anonymous) @ bootstrap:792
react-dom.development.js:12339 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(App)
printWarning @ react-dom.development.js:12339
lowPriorityWarningWithoutStack @ react-dom.development.js:12360
module.exports../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:12536
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:25646
commitRootImpl @ react-dom.development.js:24894
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12131
commitRoot @ react-dom.development.js:24888
finishSyncRender @ react-dom.development.js:24295
performSyncWorkOnRoot @ react-dom.development.js:24273
scheduleUpdateOnFiber @ react-dom.development.js:23664
updateContainer @ react-dom.development.js:27060
(anonymous) @ react-dom.development.js:27484
unbatchedUpdates @ react-dom.development.js:24399
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27483
render @ react-dom.development.js:27620
(anonymous) @ index.js:36
./app/index.js @ renderer.dev.js:7669
__webpack_require__ @ bootstrap:725
fn @ bootstrap:100
0 @ renderer.dev.js:222337
__webpack_require__ @ bootstrap:725
(anonymous) @ bootstrap:792
(anonymous) @ bootstrap:792
react-dom.development.js:21809 The above error occurred in the <App> component:
    in App (created by Connect(App))
    in Connect(App) (at app/index.js:40)
    in Route
    in Router (created by ConnectedRouter)
    in ConnectedRouter
    in Provider
    in AppContainer (at app/index.js:37)

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
logCapturedError @ react-dom.development.js:21809
logError @ react-dom.development.js:21846
callback @ react-dom.development.js:23234
callCallback @ react-dom.development.js:13811
commitUpdateEffects @ react-dom.development.js:13849
commitUpdateQueue @ react-dom.development.js:13839
commitLifeCycles @ react-dom.development.js:22101
commitLayoutEffects @ react-dom.development.js:25301
callCallback @ react-dom.development.js:337
invokeGuardedCallbackDev @ react-dom.development.js:386
invokeGuardedCallback @ react-dom.development.js:441
commitRootImpl @ react-dom.development.js:25039
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12131
commitRoot @ react-dom.development.js:24888
finishSyncRender @ react-dom.development.js:24295
performSyncWorkOnRoot @ react-dom.development.js:24273
scheduleUpdateOnFiber @ react-dom.development.js:23664
updateContainer @ react-dom.development.js:27060
(anonymous) @ react-dom.development.js:27484
unbatchedUpdates @ react-dom.development.js:24399
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27483
render @ react-dom.development.js:27620
(anonymous) @ index.js:36
./app/index.js @ renderer.dev.js:7669
__webpack_require__ @ bootstrap:725
fn @ bootstrap:100
0 @ renderer.dev.js:222337
__webpack_require__ @ bootstrap:725
(anonymous) @ bootstrap:792
(anonymous) @ bootstrap:792
react-hot-loader.development.js:294 Error: ENOENT: no such file or directory, scandir '/resources/mac/helpers/'
    at Object.readdirSync (fs.js:854)
    at Object.fs.readdirSync (electron/js2c/asar.js:605)
    at Object.fs.readdirSync (electron/js2c/asar.js:605)
    at checkVersion (drivers.darwin.js:88)
    at App.componentWillMount (App.js:115)
    at callComponentWillMount (react-dom.development.js:14253)
    at mountClassInstance (react-dom.development.js:14356)
    at updateClassComponent (react-dom.development.js:18394)
    at beginWork$1 (react-dom.development.js:20160)
    at HTMLUnknownElement.callCallback (react-dom.development.js:337)
error @ react-hot-loader.development.js:294
componentDidCatch @ react-hot-loader.development.js:2404
callback @ react-dom.development.js:23239
callCallback @ react-dom.development.js:13811
commitUpdateEffects @ react-dom.development.js:13849
commitUpdateQueue @ react-dom.development.js:13839
commitLifeCycles @ react-dom.development.js:22101
commitLayoutEffects @ react-dom.development.js:25301
callCallback @ react-dom.development.js:337
invokeGuardedCallbackDev @ react-dom.development.js:386
invokeGuardedCallback @ react-dom.development.js:441
commitRootImpl @ react-dom.development.js:25039
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12131
commitRoot @ react-dom.development.js:24888
finishSyncRender @ react-dom.development.js:24295
performSyncWorkOnRoot @ react-dom.development.js:24273
scheduleUpdateOnFiber @ react-dom.development.js:23664
updateContainer @ react-dom.development.js:27060
(anonymous) @ react-dom.development.js:27484
unbatchedUpdates @ react-dom.development.js:24399
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27483
render @ react-dom.development.js:27620
(anonymous) @ index.js:36
./app/index.js @ renderer.dev.js:7669
__webpack_require__ @ bootstrap:725
fn @ bootstrap:100
0 @ renderer.dev.js:222337
__webpack_require__ @ bootstrap:725
(anonymous) @ bootstrap:792
(anonymous) @ bootstrap:792
react-hot-loader.development.js:2411 Uncaught Error: ENOENT: no such file or directory, scandir '/resources/mac/helpers/'
    at Object.readdirSync (fs.js:854)
    at Object.fs.readdirSync (electron/js2c/asar.js:605)
    at Object.fs.readdirSync (electron/js2c/asar.js:605)
    at checkVersion (drivers.darwin.js:88)
    at App.componentWillMount (App.js:115)
    at callComponentWillMount (react-dom.development.js:14253)
    at mountClassInstance (react-dom.development.js:14356)
    at updateClassComponent (react-dom.development.js:18394)
    at beginWork$1 (react-dom.development.js:20160)
    at HTMLUnknownElement.callCallback (react-dom.development.js:337)
handleErrorFromBinding @ internal/fs/utils.js:219
readdirSync @ fs.js:854
fs.readdirSync @ electron/js2c/asar.js:605
fs.readdirSync @ electron/js2c/asar.js:605
checkVersion @ drivers.darwin.js:88
componentWillMount @ App.js:115
callComponentWillMount @ react-dom.development.js:14253
mountClassInstance @ react-dom.development.js:14356
updateClassComponent @ react-dom.development.js:18394
beginWork$1 @ react-dom.development.js:20160
callCallback @ react-dom.development.js:337
invokeGuardedCallbackDev @ react-dom.development.js:386
invokeGuardedCallback @ react-dom.development.js:441
beginWork$$1 @ react-dom.development.js:25737
performUnitOfWork @ react-dom.development.js:24661
workLoopSync @ react-dom.development.js:24637
performSyncWorkOnRoot @ react-dom.development.js:24236
scheduleUpdateOnFiber @ react-dom.development.js:23664
updateContainer @ react-dom.development.js:27060
(anonymous) @ react-dom.development.js:27484
unbatchedUpdates @ react-dom.development.js:24399
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27483
render @ react-dom.development.js:27620
(anonymous) @ index.js:36
./app/index.js @ renderer.dev.js:7669
__webpack_require__ @ bootstrap:725
fn @ bootstrap:100
0 @ renderer.dev.js:222337
__webpack_require__ @ bootstrap:725
(anonymous) @ bootstrap:792
(anonymous) @ bootstrap:792
react-dom.development.js:21809 The above error occurred in the <AppContainer> component:
    in AppContainer (at app/index.js:37)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:21809
logError @ react-dom.development.js:21846
update.callback @ react-dom.development.js:23198
callCallback @ react-dom.development.js:13811
commitUpdateEffects @ react-dom.development.js:13849
commitUpdateQueue @ react-dom.development.js:13837
commitLifeCycles @ react-dom.development.js:22126
commitLayoutEffects @ react-dom.development.js:25301
callCallback @ react-dom.development.js:337
invokeGuardedCallbackDev @ react-dom.development.js:386
invokeGuardedCallback @ react-dom.development.js:441
commitRootImpl @ react-dom.development.js:25039
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12131
commitRoot @ react-dom.development.js:24888
finishSyncRender @ react-dom.development.js:24295
performSyncWorkOnRoot @ react-dom.development.js:24273
(anonymous) @ react-dom.development.js:12181
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12131
flushSyncCallbackQueueImpl @ react-dom.development.js:12176
flushSyncCallbackQueue @ react-dom.development.js:12164
unbatchedUpdates @ react-dom.development.js:24405
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27483
render @ react-dom.development.js:27620
(anonymous) @ index.js:36
./app/index.js @ renderer.dev.js:7669
__webpack_require__ @ bootstrap:725
fn @ bootstrap:100
0 @ renderer.dev.js:222337
__webpack_require__ @ bootstrap:725
(anonymous) @ bootstrap:792
(anonymous) @ bootstrap:792
Show 3 more frames
react-dom.development.js:12194 Uncaught Error: ENOENT: no such file or directory, scandir '/resources/mac/helpers/'
    at Object.readdirSync (fs.js:854)
    at Object.fs.readdirSync (electron/js2c/asar.js:605)
    at Object.fs.readdirSync (electron/js2c/asar.js:605)
    at checkVersion (drivers.darwin.js:88)
    at App.componentWillMount (App.js:115)
    at callComponentWillMount (react-dom.development.js:14253)
    at mountClassInstance (react-dom.development.js:14356)
    at updateClassComponent (react-dom.development.js:18394)
    at beginWork$1 (react-dom.development.js:20160)
    at HTMLUnknownElement.callCallback (react-dom.development.js:337)
handleErrorFromBinding @ internal/fs/utils.js:219
readdirSync @ fs.js:854
fs.readdirSync @ electron/js2c/asar.js:605
fs.readdirSync @ electron/js2c/asar.js:605
checkVersion @ drivers.darwin.js:88
componentWillMount @ App.js:115
callComponentWillMount @ react-dom.development.js:14253
mountClassInstance @ react-dom.development.js:14356
updateClassComponent @ react-dom.development.js:18394
beginWork$1 @ react-dom.development.js:20160
callCallback @ react-dom.development.js:337
invokeGuardedCallbackDev @ react-dom.development.js:386
invokeGuardedCallback @ react-dom.development.js:441
beginWork$$1 @ react-dom.development.js:25737
performUnitOfWork @ react-dom.development.js:24661
workLoopSync @ react-dom.development.js:24637
performSyncWorkOnRoot @ react-dom.development.js:24236
scheduleUpdateOnFiber @ react-dom.development.js:23664
updateContainer @ react-dom.development.js:27060
(anonymous) @ react-dom.development.js:27484
unbatchedUpdates @ react-dom.development.js:24399
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27483
render @ react-dom.development.js:27620
(anonymous) @ index.js:36
./app/index.js @ renderer.dev.js:7669
__webpack_require__ @ bootstrap:725
fn @ bootstrap:100
0 @ renderer.dev.js:222337
__webpack_require__ @ bootstrap:725
(anonymous) @ bootstrap:792
(anonymous) @ bootstrap:792
security-warnings.ts:179 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ security-warnings.ts:179
Promise.then (async)
warnAboutInsecureCSP @ security-warnings.ts:172
logSecurityWarnings @ security-warnings.ts:295
loadHandler @ security-warnings.ts:312
async function (async)
loadHandler @ security-warnings.ts:311
client:48 [WDS] Hot Module Replacement enabled.
client:52 [WDS] Live Reloading enabled.
client?ab20:48 [WDS] Hot Module Replacement enabled.
client?ab20:52 [WDS] Live Reloading enabled.

**Comment by gniezen** [comment]
@EugeneChiang123 I identified an issue with developer builds on macOS - please merge the fix in branch `mac-dev-fix` (see #1094 for details) and try again.

For the `yarn build` without packaging, the error is due to the auto-update process used by electron-builder. [According to their docs](https://www.electron.build/auto-update#debugging):

> Note that in order to develop/test UI/UX of updating without packaging the application you need to have a file named dev-app-update.yml in the root of your project, which matches your publish setting from electron-builder config (but in yaml format).

**Comment by gniezen** [comment]
Note: `mac-dev-fix` will be merged into `develop` as part of [UPLOAD-307].

**Comment by gniezen** [comment]
macOS fix has now been merged into `develop`, so just do a `git pull` instead of merging `mac-dev-fix`.

**Comment by EugeneChiang123** [comment]
@gniezen I just pulled and ran the set of commands.
I am still getting 
Failed to load resource: net::ERR_CONNECTION_REFUSED

Error: Error: ENOENT: no such file or directory, open '/Users/eugenechiang/Tidepool/new_uploader/uploader/app/dev-app-update.yml'

On the browser side, it shows "We can't connect to Tidepool right now. Quit & relaunch the Uploader to try again." I've relaunched several times.

**Comment by EugeneChiang123** [comment]
@gniezen I just pulled and ran the set of commands.
I am still getting 
Failed to load resource: net::ERR_CONNECTION_REFUSED

Error: Error: ENOENT: no such file or directory, open '/Users/eugenechiang/Tidepool/new_uploader/uploader/app/dev-app-update.yml'

On the browser side, it shows "We can't connect to Tidepool right now. Quit & relaunch the Uploader to try again." I've relaunched several times.

**Comment by gniezen** [comment]
@EugeneChiang123 To which servers are you trying to connect? If you are running the Tidepool backend locally (see https://github.com/tidepool-org/development/tree/k8s-stable for details), run `config/device-debug.sh` to point the Uploader at your local setup. If you're developing and making changes to the Uploader, please do not use our production server, but use the integration server instead. To do this, run `config/integration.sh` to use the integration servers, which you can access at https://int-app.tidepool.org. 

If you're still seeing the `Error: Error: ENOENT: no such file or directory, open '/uploader/app/dev-app-update.yml'` error, I"m guessing you tried running without packaging again, so I'll refer you to the second part of my comment here: https://github.com/tidepool-org/uploader/issues/1017#issuecomment-595719126 . Rather use `yarn dev` to start the Uploader when running/developing locally.
