### ISSUE TITLE
Carb ratio always zero on 640g

### ISSUE THREAD

**Issue by nitsch** [tidepool-org/uploader#1036]
Fetching data from a Medtronic 640g pump via a Contour Next Link 2.4 always reports carb ratios of 0. The start times are matching the settings in the Bolus Wizard (which indicates that it is looking in the right place), but the actual factors are 0 for all of the entries.

I can observe this behaviour in the most recent version as well as in a couple of previous ones. I did not go back far enough to find a release that had this working but did not try a whole lot of versions either.

**Comment by nitsch** [comment]
I investigated a little bit and found the second field (currently documented as "unknown bytes" and "always zero") to hold the values while the first field (which is used in the current code) is always zero.

As far as I can tell, the description of the packet in the docs correctly guesses that these fields are for grams (offset 0x06) and exchanges (offset 0x0a), respectively, since my pump uses exchanges as carb unit, not grams. It lists these factors as "Exchange Ratio" in the settings and interprets the numbers as "units per exchange". Well, actually it does not since the pump is not in English, but these are the phrases according to the English manual. ;-)

The value read from the packet needs to be divided by 100 to yield "units per exchange".

I would have prepared a pull request that adds handling of this value. But using "Exchange Ratio" instead of "Carb Ratio" depending on the pump settings seems to require quite a bit of changes throughout the code base which I am not confident I can do properly (no experience with nodejs whatsoever). Maybe @pazaan can help out here?

**Comment by gniezen** [comment]
Hi @nitsch, nice sleuthing! I'm going to look into this and get back to you. We are currently tracking this issue here: https://tidepool.atlassian.net/browse/WEB-202

**Comment by gniezen** [comment]
OK, I have been able to confirm that this affects the current pump settings of 630G/640G pumps and have created a bug ticket for the Uploader [UPLOAD-282]. 

I've got a fix ready and hope to get it merged soon. Thanks for the updates to our documentation (#1037) @nitsch , I'll get that merged right away.

**Comment by gniezen** [comment]
This was fixed in Uploader v2.26.0, released 2020-02-18.
