### ISSUE TITLE
"See Data" fails on Windows 10, Tidepool Uploader v2.28.0

### ISSUE THREAD

**Issue by nickgarvey** [tidepool-org/uploader#1136]
Just performed an update, I'm not sure what prior version I was on. Data uploads fine, and I can see it when doing directly to the site, but the "See Data" button doesn't work. Obviously some issue with the space in the path.

![image](https://user-images.githubusercontent.com/1054474/79061586-85a59e00-7c46-11ea-9cf3-c4783f35bb08.png)

**Comment by krystophv** [comment]
Thanks for reporting this, we're tracking the issue at: [UPLOAD-325]

**Comment by nickgarvey** [comment]
Sounds good, feel free to close this if tracked elsewhere

**Comment by nickgarvey** [comment]
Also to be clear on the ticket - this isn't just confusion - the "See data" button doesn't work.

**Comment by loudestnoise** [comment]
Thanks again for reporting this @nickgarvey. We corrected this with version 2.28.1 of Tidepool Uploader.

You can download this version by launching Tidepool Uploader and waiting for the update, or by downloading it directly from https://www.tidepool.org/download.
