### ISSUE TITLE
Make a Dockerfile

### ISSUE THREAD

**Issue by atombrella** [tidepool-org/uploader#1238]
This is one of the few (if not the only) Tidepool app that does not have an official Docker image on Docker hub.

I prepared a rough draft here, that we need to check if it works correctly. I'm working with Tidepool through a project with a client. Tidepool looks like a very interesting project.
https://github.com/tidepool-org/uploader/compare/master...atombrella:dockerfile?expand=1

**Comment by gniezen** [comment]
Hi @atombrella ! As Uploader is a desktop app that gets built on Travis (macOS version) and Appveyor (Windows version), we've never had any need for a Docker image. Could you please explain the use case in which a Docker image is necessary?

**Comment by atombrella** [comment]
For development reasons, it'd be nice to easily spin it up in docker container, so you don't need to tamper with your local system, to install nvm, node and yarn etc. It apparently only runs in Ubuntu (the node docker image is based Debian), which is the most important reason for the docker container. @thedukedk opened a PR #1244 to address this.

**Comment by gniezen** [comment]
PR linked above has now been merged.
