### ISSUE TITLE
what should i do with this,im puzzled with this

### ISSUE THREAD

**Issue by pauloved** [tidepool-org/uploader#1240]
![image](https://user-images.githubusercontent.com/20351530/86190367-c7bfeb00-bb76-11ea-830f-75dbfd674ac8.png)
every time run `yarn dev` ,i must run `cd app`  and `yarn` before
anyone can help me ！！！thanks

**Comment by gniezen** [comment]
Hi @pauloved ! It appears there's a module for the wrong version of Node.js installed. Try this:

- remove the `node_modules` folder in both the main directory and  `app`
- **make sure you're running Node v12**
- run `yarn` in the main directory to install the modules
- try running `yarn dev` again

**Comment by pauloved** [comment]
> Hi @pauloved ! It appears there's a module for the wrong version of Node.js installed. Try this:
> 
> * remove the `node_modules` folder in both the main directory and  `app`
> * **make sure you're running Node v12**
> * run `yarn` in the main directory to install the modules
> * try running `yarn dev` again

thanks @gniezen,I tryed many times , i make sure node is v12.13.0 and electron@8.3.2 ，but not work
the error always like issue #1017 
![image](https://user-images.githubusercontent.com/20351530/86228552-17c39f80-bbc1-11ea-98cc-53c81b0411ee.png)
![image](https://user-images.githubusercontent.com/20351530/86228589-2316cb00-bbc1-11ea-871b-2517165eb04c.png)

**Comment by gniezen** [comment]
Some things that come to mind:

- Are you using the latest `master` branch?
- Are you also running `npm install`? You should only use `yarn` to install modules
- Make sure you delete both the `node_modules` directories before running `yarn`
- Which version of Windows (and 32-bit or 64-bit) are you using?

**Comment by pauloved** [comment]
> Some things that come to mind:
> 
> * Are you using the latest `master` branch?
> * Are you also running `npm install`? You should only use `yarn` to install modules
> * Make sure you delete both the `node_modules` directories before running `yarn`
> * Which version of Windows (and 32-bit or 64-bit) are you using?

64-bit，i find a strange thing ，after run` yarn`,the powershell stop in here
![image](https://user-images.githubusercontent.com/20351530/86309446-52bfe480-bc4e-11ea-8d5c-0ca230be2b63.png)
all the time

**Comment by gniezen** [comment]
Sometimes it does wait there for a while before finishing, as there are a lot of dependencies to isntall. Maybe you can run `yarn --verbose` to see what exactly is happening?

**Comment by krystophv** [comment]
The issue happens when the version of `node` used to compile a dependency doesn't match the version running under `electron`. The `electron-builder install-app-deps` command needs to complete because that's the command which will compile the native dependencies for the `electron`-specific version of `node` instead of the version which is globally installed.

**Comment by pauloved** [comment]
> The issue happens when the version of `node` used to compile a dependency doesn't precisely match the version running under `electron`. The `electron-builder install-app-deps` command needs to complete because that's the command which will compile the native dependencies for the `electron`-specific version of `node` instead of the version which is globally installed

**Comment by pauloved** [comment]
> The issue happens when the version of `node` used to compile a dependency doesn't precisely match the version running under `electron`. The `electron-builder install-app-deps` command needs to complete because that's the command which will compile the native dependencies for the `electron`-specific version of `node` instead of the version which is globally installed.

i make sure  node v12.13.0  yarn  1.22.4 ,but `yarn dev` did not complete, have no idea
