### ISSUE TITLE
How to create Windows executable?

### ISSUE THREAD

**Issue by usko1** [tidepool-org/uploader#1249]
Dear Tidepool community :-)
I would ask you if there is a way to create a windows executable? I am able to get the uploader run on windows 10 as described in the Readme (with npm run dev). However, i am wondering how to create an executable and start it as standard windows application? 
I know, i can download the Uploader and install it. But i would like to do it myself :-)

Thanks
Patrik

**Comment by gniezen** [comment]
Hi @usko1 ! You should be able to do this using `yarn package`. Let me know if you run into any issues.

**Comment by usko1** [comment]
Great, thanks. It worked. I assume it is the same for mac, right?

**Comment by gniezen** [comment]
Some things to try:

- make sure you're using Node v12.13.0
- remove the `node_modules` folder in both the main directory and  `app`
- run `yarn` in the main directory to install the modules
- try running `yarn dev` and/or `yarn package` again
