### ISSUE TITLE
CLI for Insulet fails as it's now a module

### ISSUE THREAD

**Issue by michaelcadilhac** [tidepool-org/uploader#1376]
The [README file](https://github.com/tidepool-org/uploader/blob/master/lib/drivers/insulet/cli/README.md) of the CLI module for the Omnipod indicates that it can be used on the command line.  This however fails with:

```
SyntaxError: Cannot use import statement outside a module
```

Trying to circumvent this has been a bit of a nightmare—using babel and whatnots—any simple way to do so?

**Comment by gniezen** [comment]
Yes! From the base uploader directory, use the following:

```
node -r @babel/register lib/drivers/insulet/cli/ibf_loader.js -f </path/to/Insulet-file.ibf> -u <username> -p <password>
```

**Comment by michaelcadilhac** [comment]
That's splendid Gerrit, thanks a bunch.
