### ISSUE TITLE
Uploader error for dual boluses with value 0

### ISSUE THREAD

**Issue by EyalEliyahu** [tidepool-org/uploader#1383]
Hey all :)
I've played lately with the Uploader and come across an error that I think is a bug.
I'm a diabetic myself and use Medtronic 640 pump.

Yesterday, I made a small dual bolus and then accidentally canceled it right away so that the actual amount delivered was zero.
When I tried to upload my pump data with the uploader I came across the following error:
![image](https://user-images.githubusercontent.com/4853877/118611181-3c1e6f80-b7c5-11eb-8e44-df72fcb2076c.png)
Is it correct to fail all the relevant data chuck instead of just popping the 'falsy' entry?
This is how the bad entry looks like:
``` js
{
time: "2021-05-16T19:18:21.000Z"
timezoneOffset: 180
clockDriftOffset: 0
conversionOffset: 0
deviceTime: "2021-05-16T22:18:21"
deviceId: "MMT-1712:NG2118510H"
type: "bolus"
subType: "dual/square"
normal: 0
extended: 0
duration: 0
expectedExtended: 2.1
expectedDuration: 7200000
payload: {logIndices: [2184761899]}
}
```

Please let me know if there is any more needed information and thanks for the great work! :)

**Comment by gniezen** [comment]
Hi @EyalEliyahu ! This is a known issue, and there's a backend fix ready for deployment: https://tidepool.atlassian.net/browse/BACK-1914

When data fails backend validation, we don't upload any of the data, as only uploading some entries would cause gaps that could lead to incorrect interpretation of the data.

I'm closing this as it's a backend issue, and will ask that the fix be deployed ASAP.
