### ISSUE TITLE
t:slim x2 - Unhandled combination of basal change types

### ISSUE THREAD

**Issue by eksime** [tidepool-org/uploader#1385]
When uploading from her t:slim x2 pump on fw Carlsbad v6.4 my partner is receiving the error "Unhandled combination of basal change types"

This appears to be coming from the [`buildBasalRecords(data, records)`](https://github.com/tidepool-org/uploader/blob/3e354aa6f06093c1602abf016a0cbdd4cce692b2/lib/drivers/tandem/tandemDriver.js#L1896-L1981) function in tandemDriver.js.

The [`BASAL_CHANGE_TYPE_FLAGS`](https://github.com/tidepool-org/uploader/blob/3e354aa6f06093c1602abf016a0cbdd4cce692b2/lib/drivers/tandem/tandemDriver.js#L53-L61) enum appears to be missing change type 128 (0x80) as seen in this record:

```
index: 33740
header_id: 3
header_ts: 421666628
header_log_seq_no: 33740
header_spare: 33693
rawTimestamp: 1620812228000
jsDate: Wed May 12 2021 10:37:08 GMT+0100 (British Summer Time) {}
deviceTime: "2021-05-12T09:37:08"
command_basal_rate: 2.8
base_basal_rate: 1.4
max_basal_rate: 3
idp: 0
change_type: 128
name: "Basal Rate Change Event"
change_types: []
```

As far as she knows this record was a result of changing her max basal rate while running a temp basal that was greater than the old max. Increasing the max rate uncapped her temp basal rate, making it jump from 2.0 (previous max) to 2.8.

It's possible this is not the cause, but the timing lines up, and the reasoning seems to be sensible.

**Comment by gniezen** [comment]
Thanks for the great issue report @eksime ! Change type 128 is not documented in the Tandem spec, valid values are 0-127. I'll reach out to them and try to find out what's going on.
