### ISSUE TITLE
FreeStyle Libre CSV upload

### ISSUE THREAD

**Issue by dmgawel** [tidepool-org/uploader#1388]
Hi!

Fresh T1D here. I'm using FreeStyle Libre 1 with official LibreLink app (without external reader). I recently noticed that [LibreView](https://www.libreview.com/) (free reporting and data sharing software from Abott for Libre devices) offers data exporting in CSV format. Exported file contains automated measurements (at 15m intervals), manual scans, insulin injections and carbs.

It seems to me that leveraging LibreView CSV export would be a great solution for supporting Libre 1 sensors used without external reader and Libre 2 & 3 as well (though not in a continuous data sending mode).

What do you think?

**Comment by gniezen** [comment]
Hi Dawid! The last time we allowed CSV imports (of Medtronic Carelink data at the time) it would break every so often when the CSV format changed. That said, it's definitely something we can look into again.

**Comment by dmgawel** [comment]
Oh, I see. I understand that keeping up with format changes made by providers without notice can be challenging.

Nonetheless, it's great to hear you'll look into it. Let me know if there's any way I can help you (provide sample data?).

By the way, from my perspective it would be a feasible solution to have a generic CSV upload with format specified by Tidepool Uploader. I could then transform CSV provided by LibreView on my own. Would that work for you as MVP? ;-)

**Comment by gniezen** [comment]
> By the way, from my perspective it would be a feasible solution to have a generic CSV upload with format specified by Tidepool Uploader. I could then transform CSV provided by LibreView on my own. Would that work for you as MVP? ;-)

That is an option. I'll look into this and get back to you.

**Comment by kpouget** [comment]
Hello here, any update on this topic? 

I just got LibreView (v2) data in CSV, and I really would like to see them in TidePool!

> it would be a feasible solution to have a generic CSV upload with format specified by Tidepool Uploader.

I fully agree with that, if the CSV format keeps changing, it can be easier to had a common format coded in TidePool, and then simple conversion scripts to rewrite CGM exports.

> The last time we allowed CSV imports ...

sounds like there is already some code written somewhere, do you know if this is still around?
it would be great if there were some code to study, to better understand if I could work on a generic version

**Comment by gniezen** [comment]
Hi @kpouget ! The place to look for the CSV import code is in the https://github.com/tidepool-org/uploader/tree/master/lib/drivers/carelink folder, but it hasn't been touched in years, so not sure how much of it will still be useful.

If you'd like to contribute to Uploader, the best place to start is here: https://developer.tidepool.org/uploader/

I hope to have an update on this soon.

**Comment by kpouget** [comment]
great, thanks for the link @gniezen, I'll give it a try asap (JS isn't what I usually have after diner, but I'll force myself into it :-))

I'll try first to have something working with the current CSV format exported by `libreview`, and if I can get this, then we'll be able to discuss a more generic format!

**Comment by gniezen** [comment]
The Tidepool data model is here: https://developer.tidepool.org/data-model/

CGM readings are here: https://developer.tidepool.org/data-model/device-data/types/cbg.html

**Comment by gniezen** [comment]
@kpouget Which CLI are you using, and what errors are you getting? As Node v12 doesn't yet support ES6 imports, you'll have to use `@babel/register`, e.g. `node -r @babel/register lib/drivers/insulet/cli/ibf_loader.js`

**Comment by kpouget** [comment]
@gniezen great, I know the answer would be simple and I was going the wrong way :-)

```
# works as expected
node -r @babel/register lib/drivers/insulet/cli/ibf_loader.js

# doesn't work at all
cd lib/drivers/insulet/cli/
node -r @babel/register ibf_loader.js
```

time to look at what I can get out of [`drivers/carelink/cli/csv_loader.js`](https://github.com/tidepool-org/uploader/blob/master/lib/drivers/carelink/cli/csv_loader.js) then!

**Comment by kpouget** [comment]
ok, first kick given, I can get the CSV lines parsed (the comma separated values, not the content 🙃)
```
{
  Device: 'FreeStyle LibreLink',
  'Serial Number': '...',
  'Device Timestamp': '....,
  'Record Type': 0,
  'Historic Glucose mg/dL': 136,
  'Scan Glucose mg/dL': '',
  'Non-numeric Rapid-Acting Insulin': '',
  'Rapid-Acting Insulin (units)': '',
  'Non-numeric Food': '',
  'Carbohydrates (grams)': '',
  'Carbohydrates (servings)': '',
  'Non-numeric Long-Acting Insulin': '',
  'Long-Acting Insulin Value (units)': '',
  Notes: '',
  'Strip Glucose mg/dL': '',
  'Ketone mmol/L': '',
  'Meal Insulin (units)': '',
  'Correction Insulin (units)': '',
  'User Change Insulin (units)': ''
}
```
so next step is to give this information to the core libraries below ... that will be for this weekend hopefully :)

**Comment by gniezen** [comment]
Closing this issue as support for LibreView CSV uploads were added in Uploader [2.41.0](https://github.com/tidepool-org/uploader/releases/tag/v2.41.0).
