### ISSUE TITLE
v2.63.3 control-iq incremental data uploads fail

### ISSUE THREAD

**Issue by ferringb** [tidepool-org/uploader#1390]
Briefly: uploading control-IQ data throws an error when the v2.63.3 uploader is in incremental mode, but no error is thrown if one switches the uploader to 'all' mode.  I can confirm that control-iq data has made it into the web app, but I can't confirm if that occurred before or after I switched to 'all' mode; specifically, I don't know if the incremental uploader actually worked, but just threw a noisy error.  My suspicion is 'all' is what got the data in there.

Either way, from the UI, this is all I get:
![image](https://user-images.githubusercontent.com/1531180/120372642-49ab1d80-c2cc-11eb-9bce-97b3a77391ac.png) .

Forcing drivermanager debug mode, this is what I find in the console: 
![image](https://user-images.githubusercontent.com/1531180/120374300-3f8a1e80-c2ce-11eb-8d11-638a7db9621f.png)

Note that stack trace is taken from commit tag v2.63.3.  That's pretty much it; there isn't anything else I can find in the console logs.

The pump in question is `firmware_version: 105900, deviceModel: "1002717"` .  If you need more identifiable information please ping me and I can privately share whatever logs/ID's you may need to trace this.

If you need me to retry something, or pull a trace ID out of the session- just let me know how.  I've verified this failure for both windows and linux versions, but I'm fine w/ mangling my local linux version (or trying branches) as needed if it helps.

Thanks for the integration either way; this is observability of control-iq I've been doing by hand, and this feature is greatly appreciated.

**Comment by gniezen** [comment]
As the error message says, there's not enough Control-IQ data in your incremental data for an upload. In short, we require there to be at least one change from automated to manual (or vice versa), to be able to correctly classify automated basals. You can manually trigger an automated->manual change by suspending and resuming, or perform an "all data" upload (as you already discovered).

I'm open to suggestions for making the error message clearer :wink:

**Comment by ferringb** [comment]
So... just confirming what you said via testing; I triggered an upload today, which went through fine.  Since yesterday and today I've had a suspension (cartridge change).  That worked w/out error; running the upload immediately again, that however triggered the error.  TL;DR: what you describe is exactly what I'm seeing.

As to a suggestion: I kind of strongly argue you shouldn't present this as an error to the user.  It's not an error if the user manages to stay in control-iq automation; that's actually the desired state.  :)

Better question; why does the code view this as an error?  Is it treated as an error because the 'fetch data range' function doesn't get results for control-iq, and is unable to discern if that's a failed fetch, or lack of data?  Is that a limitation of the protocol spec for tandem?

If it is a limitation- inability to tell if the fetch failed, or if there was no data- tidepool knows the last control-iq data point.  It's a blood fricking hack, and presumably annoying for your API/PII models, but the uploader could ask for the last control-iq timestamp, and then ask the pump for <that-timerange>-1...current.  I reiterate, that's hack, and I'm probably talking out of my ass here.

**Comment by gniezen** [comment]
It's a limitation of the protocol spec for Tandem. You're right that we could retrieve the last Control-IQ mode change from the backend, and that's likely what we'll have to do if we can't identify another solution with Tandem. In the meanwhile we're monitoring how often this happens, to be able to prioritise a workaround/fix. Our current assumption is that most people don't upload every day, so would have a cartridge change (or some other suspension) happening between uploads.

**Comment by ferringb** [comment]
For my particular case, I don't have any suggestion beyond what you already know.  It might be worth putting out a minor version release that tweaks the error message to clarify "this isn't an error if there is no fresh data"- I would've skipped reporting it if I saw that message, but I may not be representative of your userbase.

Either way, I appreciate the clarifications, but I don't really have a suggestion beyond the above.  You're in a rock/hard place if the firmware isn't giving you the necessary clarity.  The best I can think of is doing a "try incremental, get an error, fetch the timestamp from tidepool services, then retry w/ that timestamp to confirm error vs no data"... which is painful.

If you've got anything you want tested in regards to above, give a yell; I don't upload data daily, but I try to.

**Comment by gniezen** [comment]
This issue was fixed in v2.49.0, released 21 February 2023.
