### ISSUE TITLE
t:slim x2, temporary basal-rate  / bolus was stopped 

### ISSUE THREAD

**Issue by francis1891** [tidepool-org/uploader#1400]
hey there, first of all im in awe that this repository exist, this is just great, seems like a super useful source of info and help!
so my partner just got started with the t:slim x2, currently on firmware carlsbad v6.3, she gets random errors claiming that the   temporary basal-rate  / bolus was stopped, and she def does not initiate either of those,  it just happens.  im not sure how to extract logs from the machine but im really hoping that anyone have the faintest idea of how to tackle this? their tech support has been really useless sofar, and suggested that we turn the alarm off for this but we are 6 month pregnent and this is def out of the question, on the other hand it tends to happen in 3am which is a serious PITA :(

thank you very much for your time & effort!

**Comment by gniezen** [comment]
Hi @francis1891 ! While Tidepool Web doesn't display alarms, we do retrieve them from the pump so you should be able to see it in your data export. To export your data from Tidepool: https://support.tidepool.org/hc/en-us/articles/360044350552-Export-your-Tidepool-data

As GitHub Issues is used for reporting bugs in Tidepool's software, I'm going to close this issue, but please contact support@tidepool.org if you need any further help!
