### ISSUE TITLE
Bug: Contour next BG Meter does not support Automatic time update.

### ISSUE THREAD

**Issue by EyalEliyahu** [tidepool-org/uploader#1428]
Steps to reproduce:
1) Change patient's timezone to a different timezone.
2) Plug the Contour next BG Meter to your computer.
3) Click Upload
4) wait for the following screen to appear:
![image](https://user-images.githubusercontent.com/4853877/136217087-dadf5edc-8739-4bf5-bdbc-c4abec16b865.png)
5) press 'Automatically update'

Result:
The following screen appears and the upload has failed:
![image](https://user-images.githubusercontent.com/4853877/136217294-8470c45b-86cf-42d0-ab18-442e0e1df147.png)

Tested both on the latest MacOS and Windows Applications.
When I've opened the dev-tools panel, there is anything relevant.

Please let me know if any additional information is missing.

**Comment by gniezen** [comment]
Hi @EyalEliyahu ! Thanks for the bug report. I know that other people have experienced this as well, but I have not been able to reproduce it with the two Contour Next meters I have here. Is it possible that this is an intermittent error where the meter gets confused, and could be resolved by replugging the meter and trying to upload again? 

Would you mind sending me screenshots of the back of the meter? You're welcome to obfuscate the serial number if necessary.
