### ISSUE TITLE
Support other LibreView languages than English

### ISSUE THREAD

**Issue by GermoVeltmaat** [tidepool-org/uploader#1459]
Trying the upload option resulted in this error:
![Schermafdruk van 2021-12-20 11-37-51](https://user-images.githubusercontent.com/32248795/146755013-ab854932-0099-4bbc-b479-1a6905737c1e.png)

Possible date format problem ?

**Comment by gniezen** [comment]
This issue is being addressed by https://github.com/tidepool-org/uploader/pull/1472.

**Comment by gniezen** [comment]
Should be fixed in Uploader v2.44.0 that was just released.
