### ISSUE TITLE
LibreView import's glucose range should be 1 .1 to 27 .8 mmol/L

### ISSUE THREAD

**Issue by mrinnetmaki** [tidepool-org/uploader#1460]
@gniezen points to the correct document in https://github.com/tidepool-org/uploader/pull/1431#issuecomment-952959263. But the range on page 118

> Sensor glucose reading range | 2.2 to 27.8 mmol/L

refers to the values reported by the sensor.  The values reported by the reader (and the phone app too, I guess) to LibreView service have a wider range. The next page in the document gives you the right range:

> Blood glucose assay range | 1.1 to 27.8 mmol/L

I have sample data from LibreView that goes to 1.9 mmol/L.

**Comment by mrinnetmaki** [comment]
Pinging @kpouget too.

**Comment by mrinnetmaki** [comment]
The fix is trivial, I can make a PR too. Just let me know.

**Comment by gniezen** [comment]
Thanks @mrinnetmaki , I'll create a Jira ticket for this.

Are the values below 2.2 always from the BG meter? Or are you saying that LibreView will report sensor readings below 2.2 even though it shows up as LO on the reader? 

For directly importing data from Libre 1 readers, we've always used a lower limit of 40mg/dL ~= 2.2 mmol/L. (Data from readers are always in mg/dL, even for mmol/L readers): https://github.com/tidepool-org/uploader/blob/master/lib/drivers/abbott/freeStyleLibreConstants.js#L26

I just don't want us to record data that should be LO as actual values, even if LibreView does.

**Comment by mrinnetmaki** [comment]
The Libre reader also shows numbers like 1.9 mol/L, and not just with test strips, also when scanning with NFC.

**Comment by gniezen** [comment]
That seems odd, as according to its own manual it's not accurate at that level. Or am I misinterpreting the manual?

**Comment by mrinnetmaki** [comment]
OK, I may remember wrong. I tried, "for science" and did not manage to get values below 2.2 when scanning, rather just LOW.

**Comment by gniezen** [comment]
This issue is being addressed by https://github.com/tidepool-org/uploader/pull/1472.

**Comment by gniezen** [comment]
Should be fixed in Uploader v2.44.0 that was just released.
