### ISSUE TITLE
Is there a plan to support Contour Next One Bluetooth sync?

### ISSUE THREAD

**Issue by OrlandoLee** [tidepool-org/uploader#1515]
Hi Tidepool team!

First of all, thanks for doing all the amazing work!
I have a quick question on whether there's a plan to support Contour Next One meter sync through bluetooth.

Thanks
Orlando

**Comment by gniezen** [comment]
Hi @OrlandoLee ! We're still trying to resolve an issue with Bluetooth pairing on Windows (see https://github.com/electron/electron/issues/33111 for details), but once that is done we are planning on supporting Bluetooth uploads for all Ascensia's Bluetooth-enabled meters.
