### ISSUE TITLE
Tandem?

### ISSUE THREAD

**Issue by accessburn** [tidepool-org/uploader#1525]
Hi,

can you explain to me why the tandem driver is no longer in the directory?

**Comment by gniezen** [comment]
Apologies for the late reply on this.

We’ve implemented a policy change that moved our Tandem driver to a private repository. Moving forward, Tandem will be working directly with third parties that distribute software that connects with Tandem devices. Tidepool can introduce you to the appropriate people at Tandem to establish a direct relationship and discuss becoming a Tandem approved partner. If you’d like to move forward with this, please let us know.
