### ISSUE TITLE
Dexcom G5 Touch Screen Upload issues

### ISSUE THREAD

**Issue by jmritz** [tidepool-org/uploader#594]
When trying to upload Dexcom data using uploader 2.5.4, I was unable to get the data into Tidepool.  I selected Dexcom uploader and then the screen went white and nothing was happening.  Steps to recreate.

1.  Open uploader
2.  Select upload next to Dexcom
3.  The blank screen appears.  Nothing happens after that

Using Windows10

**Comment by pazaan** [comment]
I'm sorry to hear you're having problems uploading your Dexcom data to Tidepool. We're currently waiting on the final device protocols for the touchscreen receiver from Dexcom. As soon as we have it, we will update the Uploader to support the G5 touchscreen receiver as quickly as possible.

**Comment by 808IUFan** [comment]
I would not post pictures showing you support Dexcom if you dont support the G5 touchscreen. Gives a bad impression.

**Comment by pazaan** [comment]
We are waiting on Dexcom for the Dexcom G5 Touchscreen spec. They seem to be very busy right now. Thanks for your patience.

**Comment by gniezen** [comment]
Support for Dexcom touchscreen receivers were added in v2.20.0, released 2019-09-17.
