### ISSUE TITLE
False BG readings appearing where bolus doses occur (Tandem)

### ISSUE THREAD

**Issue by Aicos** [tidepool-org/uploader#807]
Hello!

We’re having some issues with the Tandem t:slim X2.  All the CGM reading are present. However, there seems to be false BG readings appearing at every timestamp a bolus dose has been administered (with the bolus wizard, using the CGM value to calculate the correction dose). We’re using the Tidepool Uploader v2.12 and the firmware version of the device is Pendleton v5.2.1.  Is this currently a known issue or is it new?

Thanks!

**Comment by gniezen** [comment]
Hi @Aicos ! This is a new issue - we're currently storing all BG values used in Tandem bolus calculations as "manual" readings. You're right: If the BG value is auto-populated from the CGM, we should handle this differently. I'll file a bug report.

**Comment by gniezen** [comment]
Will be fixed as part of release v2.18.0. See [UPLOAD-6] for details.

**Comment by gniezen** [comment]
Fixed in v2.18.0, released 2019-07-17.
