### ISSUE TITLE
CLI to auto fetch medtronic 600 data

### ISSUE THREAD

**Issue by thomson02** [tidepool-org/uploader#931]
My wife is a T1 diabetic and uses a medtronic 640G pump along with a Contour Next Link 2.4.

I would like to try and leverage the medtronic 600 driver to create an electron app for her that:
 - Uses the Contour Next meter to request the latest BM reading from the 640G pump on a periodic basis
 - Submit the latest reading to Tidepool
 - Display the reading (and warnings/arrows) in the system tray 
 
Such an app would allow her to discretely and proactively manage her diabetes whilst at work (in an office environment). 
 
Looking at the source code i noticed _blob_uploader.js_. However from my understanding, this code seems to only upload medtronic 600 data to tidepool. Is this correct?

Can someone give some guidance on how to extract data from the 640G pump via the Contour Next meter? I suspect that i should be looking at _driverManager.js_ in combination with _medtronic600Driver.js_ but would appreciate a push in the right direction.

**Comment by thomson02** [comment]
On further analysis it seems as though __blob_uploader.js__ may do what i required. The 'medtronic blob file path' may simply be a JSON settings file that contains both the __pumpModel__ and the __pumpSerial__.

Will check this out.

**Comment by porn** [comment]
Hey @thomson02, any news on running 640G? Same case here.

**Comment by gniezen** [comment]
Sorry for not responding to this sooner, I somehow missed this. `lib/drivers/medtronic600/cli/blob_loader.js` is used to re-upload binary data (stored as JSON files) that were previously retrieved from the pump using the Tidepool Uploader. If you enable debug mode (right-click on the login screen), you will see an option to save a binary blob when uploading a 600-series pump using the Uploader.

To actually retrieve data from the pump using the terminal, it may be more useful to look at `lib/drivers/onetouch/cli/otverio.js` as an example, and then modify it to fit the `medtronic600Driver.js` workflow.

Ideally we'd like to move the drivers out of the Uploader as separate NPM modules to make it easier to re-use.

If you're just interested in getting data off the pump, you may find this project useful: https://github.com/pazaan/decoding-contour-next-link
