### ISSUE TITLE
"npm install" fails in Linux

### ISSUE THREAD

**Issue by ondrej1024** [tidepool-org/uploader#948]
I have a similar problem as reported in issue #728 while trying to `npm install` on Ubunto18.04. Python is installed. These are the final console messages:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
npm WARN optional Skipping failed optional dependency /webpack-dev-server/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
npm WARN url-loader@2.1.0 requires a peer of webpack@^4.0.0 but none was installed.
npm WARN sinon-chai@3.2.0 requires a peer of sinon@>=4.0.0 <7.0.0 but none was installed.
npm WARN eslint-config-airbnb@16.1.0 requires a peer of eslint@^4.9.0 but none was installed.
npm WARN babel-plugin-webpack-loaders@0.9.0 requires a peer of webpack@>=1.12.9 <3.0.0 but none was installed.
npm WARN eslint-config-airbnb-base@12.1.0 requires a peer of eslint@^4.9.0 but none was installed.
npm ERR! Linux 4.15.0-60-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! lzo-decompress@0.1.2 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lzo-decompress@0.1.2 install script 'node-gyp-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lzo-decompress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lzo-decompress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lzo-decompress
npm ERR! There is likely additional logging output above.
```
Any idea how to fix this?

**Comment by ondrej1024** [comment]
`npm ERR! code ELIFECYCLE`

Is this root cause of the install failure? I am not familiar with npm. Any hint how to work around this issue would be highly appreciated?

Is anyone here successfully running the chrome uploader app on an Ubuntu machine?

Thanks for your help.

**Comment by nathanac2013** [comment]
https://drive.google.com/file/d/1SwKQRRqTeE-N63EKuiqp7J3P8lm1buRl/view?usp=drivesdk
Compiled on a 64 bit computer there's also a file called tidepool for /usr/bin , a desktop file and the debs for gksu

**Comment by ondrej1024** [comment]
Thanks for providing this tar file. I downloaded and untared it. But how do I start the application?

I looked in the provided `tidepool` bash script but this does 
`cd ~/src/chrome-uploader;`
which is a directory that does not exist on my PC. So I did `cd` into the root directrory of the package and then
`yarn run start;`
which is the second command in the bash script but I get 
`00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'`

**Comment by nathanac2013** [comment]
look in the file called inst-tidepool , theres a few things it installs , libraries and such , then if im correct i also had to do 
npm install keytar;
and npm install html somethng (read the errors its one that fails ,
then just yarn then hopefully 
yarn run start (remember to run as root so it can read your devices sorry it wasnt an extract and run thats what i was hoping for) i can try to reupload the root directory of the app if youd like

**Comment by nathanac2013** [comment]
downloaded it extracted and ran just fine ,.. only output was
nathan@nathan-HP-Stream-Laptop-11-ah0XX:/Downloads$ tar -xpf ./a.tar
nathan@nathan-HP-Stream-Laptop-11-ah0XX:/Downloads$ yarn run start
yarn run v1.17.3
$ cross-env NODE_ENV=production electron ./app/
Crash logs can be found in: /tmp/Uploader Crashes
Last crash report: null
Uploading only new records
Checking for update
Error: Error: ENOENT: no such file or directory, open '/home/nathan/Downloads/app/dev-app-update.yml'

and it opened and worked fine , for now , let me make a live disk to take out any outside factors and make a inst file for real i started to in the tar but gave up half way fixing all the errors to tell the truth

**Comment by ondrej1024** [comment]
Here is what I do:
```
$ tar -xpf ./a.tar
$ yarn run start
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
```
Probably some dependency issue.

**Comment by nathanac2013** [comment]
ok i got a script to fix that just putting in the part to make the desktop file for /usr/share/applications and its done ill upload in just a min

**Comment by nathanac2013** [comment]
#!/bin/bash
echo '===================installing dependencies===================';
sudo apt-get install -y git curl gcc g++ make libavutil-dev  libsecret-1-dev libudev-dev;
echo '=====================adding yarn repo========================';
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -;
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list;
echo '=================adding nodejs repo=======================';
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -;
sudo apt-get update;
sudo apt install -y yarn nodejs;
echo '=====================cloning source=========================';
git clone https://github.com/tidepool-org/chrome-uploader;
cd chrome-uploader;
echo '====================compiling======================='
yarn install;
yarn run build;
npm install html-webpack-plugin;
echo '======================installing into system========================';
sudo mkdir /usr/share/tidepool-uploader;
sudo tar -cpf /usr/share/tidepool-uploader/app.tar ./*;
cd ..;
rm -rf ./chrome-uploader;
cd  /usr/share/tidepool-uploader
sudo tar -xpf /usr/share/tidepool-uploader/app.tar;
sudo rm -f ./app.tar
echo '=================making tidepool command==================='
echo '#!/bin/bash' >  ~/tidepool;
echo 'cd /usr/share/tidepool-uploader' >> ~/tidepool;
echo 'yarn run start'>> ~/tidepool;
sudo chmod +x ~/tidepool;
sudo cp ~/tidepool /usr/bin/tidepool;
echo '======================installing gksu(has to run root to read usb)================================='
echo 'deb http://archive.ubuntu.com/ubuntu/ artful main universe' | sudo tee /etc/apt/sources.list.d/artful.list;
sudo apt-get update;
sudo apt-get install -y gksu;
echo '============making desktop file for your app archive(so itll show up in your menu bar)=============='
cd ~;
sudo echo '[Desktop Entry]' > tidepool.desktop
sudo echo 'Encoding=UTF-8'  >> tidepool.desktop
sudo echo 'Version=2.19.0' >> tidepool.desktop
sudo echo 'Name=Tidepool Uploader' >> tidepool.desktop
sudo echo 'Comment=tidepool uploader app' >> tidepool.desktop
sudo echo 'Exec=gksu tidepool' >> tidepool.desktop
sudo echo 'Icon=tidepool-t-logo.41feef82.png' >> tidepool.desktop
sudo echo 'Terminal=false' >> tidepool.desktop
sudo echo 'Type=Application' >> tidepool.desktop
sudo echo 'Categories=Network;Medical;Health;' >> tidepool.desktop
sudo cp ./tidepool.desktop /usr/share/applications/tidepool.desktop
mkdir ./.icons
cd .icons
wget https://www.tidepool.org/static/media/tidepool-t-logo.41feef82.png
echo '============finished:)=========='

**Comment by ondrej1024** [comment]
Tried to execute your script step by step. The first steps are working fine. Then it fails at the following command:

`yarn run build;`

with this output:
```
ERROR in RollbarSourceMapPlugin: required field, 'accessToken', is missing.
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!app/app.global.css:
       [0] ./node_modules/css-loader!./app/app.global.css 159 bytes {0} [built]
            factory:76ms building:369ms = 445ms
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/less-loader/dist/cjs.js!styles/main.less:
                                    Asset     Size  Chunks             Chunk Names
    9fce60d53554378b14921c0107d7480e.woff  19.1 kB          [emitted]  
    71c4b3129c1b036c625882343856515f.woff  14.6 kB          [emitted]  
    0ffd6c9760dbd98b33b40cda7c5fe855.woff  15.8 kB          [emitted]  
    84b1d9bb65b585d4b4a72ee9cefb2ac2.woff  15.5 kB          [emitted]  
    fde24758aebc846486a8c5a09ae9b6ec.woff  34.5 kB          [emitted]  
    6fa5c741ebb77e8755bb170b61defbe1.woff  19.3 kB          [emitted]  
    746d6b360f8f4d39b1b404cbfda7a46f.woff  18.2 kB          [emitted]  
    d3372337c333af603a2335d2c64ea768.woff    19 kB          [emitted]  
    c8cc4863dc7a03cc952ea036989bd198.woff  17.9 kB          [emitted]  
    3ccbd41bfd4962b57199a8fcfbcbde66.woff  14.5 kB          [emitted]  
    62cbdba6a7531bf78b96b300d7633885.woff  34.1 kB          [emitted]  
    2bd9265b1f8a16deada8cc403a206e4d.woff  38.4 kB          [emitted]  
    b54a961aebdbc66412714065b71e4217.woff  17.9 kB          [emitted]  
    617494c08a34bb9a65d10924be76fa83.woff  35.7 kB          [emitted]  
    64436be4a3a25e8401aebe090c1f4bd5.woff  12.6 kB          [emitted]  
    d964bcfe963647ed3ad43a09c26af4af.woff  13.4 kB          [emitted]  
    e796e19720813b05b07f4b5b1cafc642.woff  12.3 kB          [emitted]  
    e60f1db974ad7cf484e687746d90a21b.woff  12.9 kB          [emitted]  
       [0] ./node_modules/css-loader!./node_modules/less-loader/dist/cjs.js!./styles/main.less 20.2 kB {0} [built]
            factory:260ms building:2987ms = 3247ms
       [3] ./fonts/icons.woff 8.26 kB {0} [built]
           [] -> factory:706ms building:707ms = 1413ms
       [4] ./fonts/opensans.woff 83 bytes {0} [built]
           [] -> factory:706ms building:1543ms = 2249ms
       [5] ./fonts/opensans-bold.woff 83 bytes {0} [built]
           [] -> factory:706ms building:1542ms = 2248ms
       [6] ./fonts/opensans-italic.woff 83 bytes {0} [built]
           [] -> factory:707ms building:1542ms = 2249ms
       [7] ./fonts/opensans-bolditalic.woff 83 bytes {0} [built]
           [] -> factory:707ms building:1543ms = 2250ms
       [8] ./fonts/basis-grotesque-light.woff 83 bytes {0} [built]
           [] -> factory:707ms building:2799ms = 3506ms
       [9] ./fonts/basis-grotesque-light-italic.woff 83 bytes {0} [built]
           [] -> factory:707ms building:2541ms = 3248ms
      [10] ./fonts/basis-grotesque-regular.woff 83 bytes {0} [built]
           [] -> factory:707ms building:2211ms = 2918ms
      [12] ./fonts/basis-grotesque-medium.woff 83 bytes {0} [built]
           [] -> factory:708ms building:2209ms = 2917ms
      [13] ./fonts/basis-grotesque-medium-italic.woff 83 bytes {0} [built]
           [] -> factory:708ms building:2210ms = 2918ms
      [14] ./fonts/basis-grotesque-bold.woff 83 bytes {0} [built]
           [] -> factory:708ms building:2568ms = 3276ms
      [15] ./fonts/basis-grotesque-bold-italic.woff 83 bytes {0} [built]
           [] -> factory:708ms building:2569ms = 3277ms
      [16] ./fonts/basis-grotesque-black.woff 83 bytes {0} [built]
           [] -> factory:708ms building:2210ms = 2918ms
      [21] ./fonts/basis-grotesque-mono-bold-italic.woff 83 bytes {0} [built]
           [] -> factory:709ms building:1543ms = 2252ms
        + 7 hidden modules
Child html-webpack-plugin for "../app.html":
     1 asset
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./app/app.html 1.3 kB {0} [built]
            factory:25ms building:19ms = 44ms
       [2] (webpack)/buildin/module.js 495 bytes {0} [built]
           [] -> factory:3299ms building:693ms = 3992ms
        + 1 hidden module
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! tidepool-uploader@2.19.0 build-renderer: `yarn build-renderer-quiet --progress --profile --colors`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the tidepool-uploader@2.19.0 build-renderer script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ondwis/.npm/_logs/2019-09-11T12_10_02_829Z-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by ondrej1024** [comment]
Anyway,

`yarn run start`

starts the application successfully now, eventhough the build command failed. Weird but great.

**Comment by nathanac2013** [comment]
That last error in your build was fixed with the npm install command right after it is why

**Comment by ondrej1024** [comment]
OK. Thanks for sharing your work here. I guess there are many people out there who want to run the tidepool uploader on their Linux machines (like me).

**Comment by nathanac2013** [comment]
https://drive.google.com/open?id=1SozrjGejC7Q3qS1WGqNK23656MnePXxc 
heres the compiled binary

**Comment by gniezen** [comment]
Going to close this as it's now possible to run Uploader using Docker on Linux: https://github.com/tidepool-org/uploader#docker-for-linux (you don't need to use Docker to build Uploader on Ubuntu and its derivatives, but it does make it a little easier)
